### ISSUE TITLE
Artifacts in the corners of the titlebar on maximized window

### ISSUE THREAD

**Issue by rumpelsepp** [PolyMeilex/sctk-adwaita#14]
I was forwarded to this repository here, since I experience an imperfection caused by this library. To be more specific: On gnome there are artifacts present in the titlebar when the relevant window is maximized, since the background is visible (blue on my screenshot below).

![Screenshot from 2022-09-15 08-27-40](https://user-images.githubusercontent.com/1961699/190330301-b8c2f8b1-50ee-4fc6-9ba7-c37958145eb0.png)

Typically, Gnome windows (at least in the current version) disable their rounded corners when the window is maximized.

See also: https://github.com/alacritty/alacritty/issues/6338

**Comment by PolyMeilex** [comment]
Thanks for the report, should be easy to fix.

**Comment by PolyMeilex** [comment]
Fix included in new `0.5.2` and back ported to `0.4.3` version.
