### ISSUE TITLE
Release 0.6.1 and yank 0.6.0

### ISSUE THREAD

**Issue by LechintanTudor** [PolyMeilex/sctk-adwaita#34]
Hi! 👋

The current version of sctk-adwaita available on crates.io (v0.6.0), has a debug println in `Button::draw`. The latest stable version of winit (v0.28.6) depends on this crate so all winit applications that use client-side decorations fill the terminal with debug messages.

Could you please release a patch to v0.6 that addresses this issue and yank the current version so it won't affect others in the future?

**Comment by PolyMeilex** [comment]
Done
